networks:
  custom_network:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /home/ykawakit/data/wordpress
      device: ../volumes/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /home/ykawakit/data/mariadb
      device: ../volumes/mariadb

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    restart: always
    networks:
      - custom_network
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    container_name: redis
    build: requirements/bonus/redis
    image: redis
    restart: always
    networks:
      - custom_network
    volumes:
      - wordpress_data:/data
    depends_on:
      - wordpress

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    image: ftp
    restart: always
    networks:
      - custom_network
    volumes:
      - wordpress_data:/home/ykawakit/ftp/files
    depends_on:
      - wordpress
    ports:
      - 21:21
      - 20:20
      - 40000:40000
      - 40001:40001
      - 40002:40002
      - 40003:40003
      - 40004:40004
      - 40005:40005
